#ifndef VEDLIOT_VERIFIER_TA_H
#define VEDLIOT_VERIFIER_TA_H

#define VEDLIOT_VERIFIER_TA_UUID \
  { 0x526461e2, 0xd34a, 0x4d96, \
    { 0x8c, 0xa3, 0x7f, 0xb9, 0xf4, 0xb8, 0x98, 0xef } }

#define VERIFIER_COMMAND_BOOTSTRAP_SECRET 0
#define VERIFIER_COMMAND_HANDLE_MSG_0     1
#define VERIFIER_COMMAND_PREPARE_MSG_1    2
#define VERIFIER_COMMAND_HANDLE_MSG_2     3
#define VERIFIER_COMMAND_PREPARE_MSG_3    4

#endif /* VEDLIOT_VERIFIER_TA_H */
